export const DIALOG_INFO_TYPE = Object.freeze({
  DETAILS_GIG: "DETAILS_GIG",
  DELETE_JOB: "DELETE_JOB",
  CALENDAR: "CALENDAR",
  JOB_COMPLETE: "JOB_COMPLETE",
  MAKE_PAYMENT: "MAKE_PAYMENT",
  TICKET_DETAILS: "TICKET_DETAILS",
  TICKET_STATUS_CHANGE: "TICKET_STATUS_CHANGE",
  JOB_DETAILS: "JOB_DETAILS",
});
